spring:
  profiles:
    active: dev         # 当前环境
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml

server:
  tomcat:
    uri-encoding: UTF-8